contacto/urls.py
from django.urls import path


urlpatterns = [
	
	# path('', views.contacto.as_view(), name="contacto-index"),
	
	]

ecommerce/contacto/urls.py
from django.urls import path

from . import views

app_name = 'contacto'

urlpatterns = [
	path('', views.Contacto.as_view(), name="contacto"),
	path('success-contacto/', views.SuccessContacto.as_view(), name="success-contacto"),
	
	]

ecommerce/productos/urls.py
from django.urls import path
from . import views

app_name = "productos"
urlpatterns = [
	path('', views.home, name="home"),
	
	path('hombres/', views.hombres, name="categoria-hombres"),
	path('mujeres/', views.mujeres, name="categoria-mujeres"),
	path('ninos/', views.ninos, name="categoria-ninos"),
	path('agregar-producto/', views.AgregarProducto.as_view(), name='agregar-producto'),
	path('agregar-producto-success/', views.AgregarProductoSuccess.as_view(), name='agregar-producto-success'),
	
	]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
	path('admin/', admin.site.urls),
	
	# My apps
	path('', include('productos.urls')),
	path('usuarios/', include('usuarios.urls')),
	path('contacto/', include('contacto.urls')),
	
	# Third party apps
	path('accounts/', include('registration.backends.default.urls')),
	path('__debug__/', include('debug_toolbar.urls')),
	
	]
if settings.DEBUG:
	from django.conf.urls.static import static
	
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
	path('login/', views.login_page, name="login"),
	path('logout/', views.logout_page, name="logout"),
	path('register/', views.register, name="register"),
	path('mis-datos/', views.ver_datos, name='ver-datos'),
	path('mis-datos-confirmacion/', views.confirmacion_mis_datos, name='confirmacion-mis-datos')
	]

ecommerce/contacto/models.py
from django.db import models


class Consulta(models.Model):
	email = models.EmailField()
	mensaje = models.TextField()
	fecha = models.DateTimeField(auto_now_add=True)
	respondido = models.BooleanField(default=False)
	
	def __str__(self):
		return self.email


class Respuesta(models.Model):
	consulta = models.ForeignKey(Consulta, blank=True, null=True, on_delete=models.CASCADE)
	respuesta = models.TextField(blank=False, null=False)
	fecha = models.DateTimeField(auto_now_add=True, blank=True, editable=True)
	
	def create_mensaje(self):
		consulta_cambio_estado = Consulta.objects.get(id=self.consulta.id)
		consulta_cambio_estado.respondido = True
		consulta_cambio_estado.save()
	
	def save(self, *args, **kwargs):
		self.create_mensaje()
		force_update = False
		if self.id:
			force_update = True
		
		super(Respuesta, self).save(force_update=force_update)

ecommerce/productos/models.py
from django.db import models

# Create your models here.
from django.utils.html import format_html


class Producto(models.Model):
	# -------------------- Choices ------------------------------
	HO = 'HOMBRES'
	MU = 'MUJERES'
	NI = "NINOS"
	
	GENERO_CHOICES = [
		(HO, 'Hombre'),
		(MU, 'Mujeres'),
		(NI, "Ninos")
		]
	
	RO = 'ROJO'
	AZ = 'AZUL'
	VE = 'VERDE'
	AM = 'AMARILLO'
	MO = 'MOSTAZA'
	BO = 'BORDO'
	NE = 'NEGRO'
	BL = 'BLANCO'
	
	COLOR_CHOICES = [
		(RO, "Rojo"),
		(AZ, "Azul"),
		(VE, "Verde"),
		(AM, "Amarillo"),
		(MO, "Mostaza"),
		(BO, "Bordo"),
		(NE, "Negro"),
		(BL, 'Blanco')
		]
	# ---- Talles ----
	XS = "XS"
	S = "S"
	M = "M"
	L = "L"
	XL = "XL"
	XXL = "XXL"
	
	TALLES_CHOICES = [
		(XS, 'XS'),
		(S, 'S'),
		(M, 'M'),
		(L, 'L'),
		(XL, 'XL'),
		(XXL, 'XXL')
		]
	
	# ---- Productos ----
	RE = "REMERA"
	BU = "BUZO"
	CA = "CAMPERA"
	PA = "PANTALON"
	BE = "BERMUDAS"
	AC = "ACCESORIOS"
	
	PRODUCTOS_CHOICES = [
		(RE, "Remera"),
		(BU, "Buzo"),
		(CA, "Campera"),
		(PA, "Pantalon"),
		(BE, "Bermudas"),
		(AC, "Accesorios")
		
		]
	
	# -------------------- Models ------------------------------
	nombre_producto = models.CharField(max_length=50)
	imagen = models.ImageField(verbose_name='imagen')
	genero = models.CharField(verbose_name='genero', max_length=10, choices=GENERO_CHOICES)
	fecha_agregado = models.DateTimeField(verbose_name='date', auto_now_add=True)
	tipo_de_prenda = models.CharField(verbose_name='prenda', max_length=50, choices=PRODUCTOS_CHOICES)
	color = models.CharField(verbose_name='color', max_length=35, choices=COLOR_CHOICES)
	talle = models.CharField(verbose_name='talle', max_length=5, choices=TALLES_CHOICES)
	valor = models.FloatField(verbose_name='valor')
	stock = models.IntegerField(default=0)
	
	def __str__(self):
		return f"{self.id} - {self.nombre_producto}"
	
	# Stock formatted
	def stocks(self):
		if self.stock < 10:
			return format_html('<a style="color: #f00;">{}</a>', f"{self.stock}. Reponer mercaderia.")
		else: return self.stock

ecommerce/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
	usuario = models.OneToOneField(User, blank=False, null=True, on_delete=models.CASCADE)
	imagen = models.ImageField(upload_to="producto/%Y/%m/%d", default='defecto/defecto.png', blank=True, null=True)
	nombre = models.CharField(max_length=50)
	apellido = models.CharField(max_length=50)
	
	def __str__(self):
		try:
			return self.usuario.username
		
		except AttributeError:
			return f"{self.nombre} {self.apellido}"

ecommerce/contacto/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import Consulta


class ContactoForm(forms.ModelForm):
	captcha = CaptchaField()
	
	class Meta:
		model = Consulta
		fields = ['email', 'mensaje']

ecommerce/productos/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Producto


class ProductoForm(forms.ModelForm):
	class Meta:
		model = Producto
		fields = '__all__'
		exclude = ('fecha_agregado',)

ecommerce/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import UserProfile


class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ["nombre", "apellido", "imagen"]


class UserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

ecommerce/contacto/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView

from .forms import ContactoForm


class Contacto(FormView):
	template_name = 'contacto/contacto.html'
	success_url = reverse_lazy('contacto:success-contacto')
	form_class = ContactoForm
	
	def form_valid(self, form):
		form.save()
		return super().form_valid(form)


class SuccessContacto(TemplateView):
	template_name = 'contacto/success-contacto.html'

ecommerce/productos/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, TemplateView

from .forms import ProductoForm
from .models import Producto


# Create your views here.
def home(request):
	return render(request, 'productos/index.html')


def hombres(request):
	params = {}
	productos = Producto.objects.filter(Q(genero='HOMBRES'), )
	params['productos'] = productos
	
	return render(request, 'productos/categoria-hombres.html', params)


def mujeres(request):
	params = {}
	productos = Producto.objects.filter(Q(genero='MUJERES'), )
	params['productos'] = productos
	return render(request, 'productos/categoria-mujeres.html', params)


def ninos(request):
	params = {}
	productos = Producto.objects.filter(Q(genero='NINOS'), )
	params['productos'] = productos
	return render(request, 'productos/categoria-ninos.html', params)


class AgregarProducto(CreateView):
	template_name = 'productos/agregar-producto.html'
	form_class = ProductoForm
	success_url = reverse_lazy('agregar-producto-success')


class AgregarProductoSuccess(TemplateView):
	template_name = 'productos/agregar-producto-success.html'

ecommerce/usuarios/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from .forms import UserProfileForm

from .forms import UserForm


def login_page(request):
	params = {}
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		
		if user is not None:
			print(username)
			print(password)
			login(request, user)
			return redirect('productos:home')
		else:
			print('There was an error ')
			return render(request, 'usuarios/login.html', params)
	
	return render(request, 'usuarios/login.html')


def logout_page(request):
	logout(request)
	return redirect(reverse('productos:home'))


def register(request):
	params = {}
	if request.method == 'POST':
		form = UserForm(request.POST)
		if form.is_valid():
			print('La cuenta fue creada')
			form.save()
			return redirect('usuarios:login')
	else:
		form = UserForm()
	
	params['form'] = form
	
	return render(request, 'usuarios/register.html', params)


@login_required(login_url=reverse_lazy('usuarios:login'))
@transaction.atomic
def ver_datos(request):
	ctx = {}
	
	if request.method == "POST":
		user_form = UserForm(request.POST, instance=request.user)
		user_profile_form = UserProfileForm(request.POST, instance=request.user.userprofile)
		if user_form.is_valid() and user_profile_form.is_valid():
			user_form.save()
			user_profile_form.save()
			print('Form was saved')
			return redirect('usuarios:confirmacion-mis-datos')
	
	if request.method == 'GET':
		ctx['user_form'] = UserForm(instance=request.user)
		ctx['user_profile_form'] = UserProfileForm(instance=request.user.userprofile)
	
	return render(request, 'usuarios/mis-datos.html', ctx)


def confirmacion_mis_datos(request):
	return render(request, 'usuarios/editar-datos-confirmacion.html')

ecommerce/templates/base/modules/navbar.html
{% load static %}


<nav class="navbar navbar-expand-lg bg-light">


	{#	Small Screen Logo#}
	<a class="d-block  d-md-none d-sm-flex ms-auto me-auto" href="{% url 'productos:home' %}">
		<img class="" src="{% static 'img/logo.png' %}" id="logo" alt="logo">
	</a>


	<div class="container-fluid">
		<button class="navbar-toggler me-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
		        aria-controls="navbarSupportedContent"
		        aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0 ps-5">
				<li class="nav-item p-2">
					<a class="nav-link" aria-current="page" href="{% url 'productos:categoria-hombres' %}">Hombres</a>
				</li>
				<li class="nav-item p-2">
					<a class="nav-link" href="{% url 'productos:categoria-mujeres' %}">Mujeres</a>
				</li>
				<li class="nav-item p-2">
					<a class="nav-link" href="{% url 'productos:categoria-ninos' %}">Niños</a>
				</li>


			</ul>
			<a class="d-flex me-auto d-none d-lg-block" href="{% url 'productos:home' %}">
				<img class="" src="{% static 'img/logo.png' %}" id="logo" alt="logo">
			</a>


			<form class="d-flex" role="search">
				<input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
				<button class="btn" type="submit">
					<ion-icon name="search-outline"></ion-icon>
				</button>

			</form>


			{#		User Menu#}
			{% if user.is_authenticated and not user.is_superuser %}
				<a href="{% url 'usuarios:ver-datos' %}" class="d-block my-sm-3 btn shadow-none ms-3" id="btn-login">Mis Datos</a>
			{% endif %}


			{% if not user.is_superuser %}
				<a href="{% url 'contacto:contacto' %}" class="d-block my-sm-3 btn shadow-none ms-3" id="btn-login">Contacto</a>
			{% endif %}

			{#		Admin menu  #}
			{% if user.is_superuser %}
				<a href="{% url 'productos:agregar-producto' %}" class="d-block my-sm-3 btn shadow-none ms-3 mx-2" id="btn-login">Agregar
					Producto</a>
				<p class="bg-danger">Permiso de administrador</p>
			{% endif %}
			{% if not user.is_authenticated %}
				<a href="{% url 'usuarios:login' %}" class="d-block my-sm-3 btn shadow-none ms-3" id="btn-login">Login</a>
			{% endif %}
			{% if user.is_authenticated %}
				<a href="{% url 'usuarios:logout' %}" class="d-block my-sm-3 btn shadow-none ms-3" id="btn-login">Logout</a>
			{% endif %}


		</div>
	</div>
</nav>


{#<nav class="navbar navbar-expand-lg bg-light">#}
{#	<div class="container-fluid">#}
{#		<a class="navbar-brand" href="#">Navbar</a>#}
{#		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"#}
{#		        aria-expanded="false" aria-label="Toggle navigation">#}
{#			<span class="navbar-toggler-icon"></span>#}
{#		</button>#}
{#		<div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#			<ul class="navbar-nav me-auto mb-2 mb-lg-0">#}
{#				<li class="nav-item">#}
{#					<a class="nav-link active" aria-current="page" href="#">Home</a>#}
{#				</li>#}
{#				<li class="nav-item">#}
{#					<a class="nav-link" href="#">Link</a>#}
{#				</li>#}
{#				<li class="nav-item dropdown">#}
{#					<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">#}
{#						Dropdown#}
{#					</a>#}
{#					<ul class="dropdown-menu">#}
{#						<li><a class="dropdown-item" href="#">Action</a></li>#}
{#						<li><a class="dropdown-item" href="#">Another action</a></li>#}
{#						<li>#}
{#							<hr class="dropdown-divider">#}
{#						</li>#}
{#						<li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#					</ul>#}
{#				</li>#}
{#				<li class="nav-item">#}
{#					<a class="nav-link disabled">Disabled</a>#}
{#				</li>#}
{#			</ul>#}
{#			<form class="d-flex" role="search">#}
{#				<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
{#				<button class="btn btn-outline-success" type="submit">Search</button>#}
{#			</form>#}
{#		</div>#}
{#	</div>#}
{#</nav>#}